# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: youth_read-1

on:
  workflow_dispatch:
  schedule:
     - cron: '6 3,7,19,23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ_17 }}
      YOUTH_READ2: ${{ secrets.YOUTH_READ_18 }}
      YOUTH_READ3: ${{ secrets.YOUTH_READ_19 }}
      YOUTH_READ4: ${{ secrets.YOUTH_READ_20 }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读一】'
        if: env.YOUTH_READ
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_17 }}

      - name: '运行 【中青看点自动阅读二】'
        if: env.YOUTH_READ2
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_18 }}
          
      - name: '运行 【中青看点自动阅读三】'
        if: env.YOUTH_READ3
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_19 }}
          
      - name: '运行 【中青看点自动阅读四】'
        if: env.YOUTH_READ4
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_20 }}
